### ISSUE TITLE
Demo 148 - Error in Model Update

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#782]
@choper725 lets continue here with:
https://github.com/abap2UI5/abap2UI5/pull/778#issuecomment-1890745772

<img width="734" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/291e1e08-33b3-4c5a-a6f4-16aeec87ec07">

**Comment by oblomov-dev** [comment]
the demo 148 is big, which makes finding the error difficult. i created a separated minimal example to check the binding:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_153.clas.abap

i think i fixed the issue:
https://github.com/abap2UI5/abap2UI5/pull/783

but if not can you change the structure here to reproduce your error case:
https://github.com/abap2UI5/abap2UI5-samples/blob/031f56d4a1466479d63a918df3a5bc0eab27fbc8/src/z2ui5_cl_demo_app_153.clas.abap#L20

i fixed this position, but i am sure we need this somewhere else so i believe i created a new error now:
https://github.com/abap2UI5/abap2UI5/blob/83393c3fcf8a256073c5855f88172c91b5ddeb60/src/00/z2ui5_cl_util_func.clas.abap#L649

these binding issues are always complicated to identify but step by step we can will make it.

**Comment by choper725** [comment]
hi @oblomov-dev 

i still dont get the border_width and border_radius on update model.. :\

**Comment by oblomov-dev** [comment]
Hi @choper725,

For me this still looks like a problem at the frontend, in the request body the attributes are written without underscore:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/baa69efd-3eb9-4c07-b63a-47a14a59eeb9">

But when you check the ms_db-t_attri table of abap2UI5 you see that the framework expects the attributes with underscore:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/df239e50-095c-4355-870a-dceaa290ea9d">

I added a demo 153 (z2ui5_cl_demo_app_153) where i make the binding with nested structures and tables, there you can see that it works:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/a4bf4926-dec6-4ef3-ad0e-9209783c9429">

Demo 148 is very big, t_attri with a lot of entries and the payload of the body has a lot of entries too, if possible try to reproduce your problem with demo 153 which makes it a lot easier to debug and to identify the root cause.

Let me know if this works for you or you need more assistance.

Best regards.

**Comment by choper725** [comment]
with latest PR in samples repository i updated demo 153 with the logic i use in the chartjs demo 148..

updated the chiled table with new property (new_type), and binded the table with pretty_name = 'X'.

**Comment by oblomov-dev** [comment]
Added now additional logic fore binding in pretty mode. The demo 153 works now, you can try again, and please just extend demo 153 if you run into further problems.

<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/459b64a2-236e-4b9e-9932-14d729517458">

**Comment by choper725** [comment]
hi @oblomov-dev 
it was still not working on chartjs,
so what i saw that its another level down the nested route,
so i made another nest on top of the new_type field in demo 153,

no the demo is getting an abap error..

**Comment by oblomov-dev** [comment]
thank you for updating the demo. made a fix https://github.com/abap2UI5/abap2UI5/pull/788
demo works now again on my side

**Comment by choper725** [comment]
well its still not working on chartjs...
 i know its hard to debug demo148, but im out of ideas and maybe you can point me to where should i look,
the break is on the setConfig method, before any frontend logic,,

on first load:
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/d6e7478a-cda9-433e-8102-dd209a84d359)
see borderWidth and borderRadius are there,

on update, they are gone, 
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/ad6f5826-f2ef-4028-93f1-bc35c6ca3001)

**Comment by oblomov-dev** [comment]
Thank you for the update of 153. Fixed the binding again with https://github.com/abap2UI5/abap2UI5/pull/791
Works now on my side.

**Comment by choper725** [comment]
yes! now its working..! thanks for the quick fixes @oblomov-dev !
ill continue working on implementing chartjs library, ill leave this for a bit to see if i encounter any more binding issues

**Comment by choper725** [comment]
hi @oblomov-dev 

after latest pull, nothing is working on my side.. not really sure what it is exacly,
just getting this: (4 times on each chart)
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/d538946e-fac6-4493-a0da-b844f42d4b85)

**Comment by oblomov-dev** [comment]
yes already saw it here:
https://github.com/abap2UI5/abap2UI5/pull/796#issuecomment-1902038676

But popus work on my side, only chart.js is not working...

**Comment by oblomov-dev** [comment]
EDIT: there was only a change in the compress functionality, so maybe you test again with client->_bind_edit( ... compress = abap_false) in case you use this. but no other changes were made.

**Comment by choper725** [comment]
> EDIT: there was only a change in the compress functionality, so maybe you test again with client->_bind_edit( ... compress = abap_false) in case you use this. but no other changes were made.

yes i do used it as true, not false

**Comment by oblomov-dev** [comment]
yes every variable typed with abap_bool is now not compressed anymore and values are with "false" send to the frontend.

If you still get problems after deactivating compress it might be because your data model does now contain initial values and the position of arrays etc might be changed now.

**Comment by choper725** [comment]
means that every type abap book is being sent to frontend with value false unless its set to true ??

**Comment by oblomov-dev** [comment]
yes abap_bool becomes true or false at the frontend but is not initial anymore, otherwise certain UI5 controls are not working properly, when compress is activated.

you also have the option to deactivate compress or is this not working?

another option can be that we extend the framework with another parameter like "compress_without_booleans". 

or last option: you can test with using type "xflag" instead of "abap_bool". i deactivated compress for this with the last PR:
https://github.com/abap2UI5/abap2UI5/blob/4a57ef5ef7b2da15edce925c880ec179845778fe/src/00/z2ui5_cl_util_func.clas.abap#L327

**Comment by choper725** [comment]
> yes abap_bool becomes true or false at the frontend but is not initial anymore, otherwise certain UI5 controls are not working properly, when compress is activated.
> 
> you also have the option to deactivate compress or is this not working?
> 
> another option can be that we extend the framework with another parameter like "compress_without_booleans".
> 
> or last option: you can test with using type "XFELD" instead of "abap_bool". i deactivated compress for this with the last PR:
> 
> https://github.com/abap2UI5/abap2UI5/blob/4a57ef5ef7b2da15edce925c880ec179845778fe/src/00/z2ui5_cl_util_func.clas.abap#L327

thx for the quick reply,
XFELD is acting wierd, some boolean values i change not getting sent to frontend...
i think the most elegant solution to this i do create another parameter like full_compress which make it act full compress with all types

**Comment by oblomov-dev** [comment]
ok great that this works for you, looks very nice:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/d4c2939c-b251-41a0-922a-48cf806d8799">

yes the weird behaviour is the behauviour of /ui2/cl_json, when a structure is completely empty even with false, it is not created. i mean i could extend the /ui2/cl_json class again but i think for now it is fine like this.

the XFELD approach was just for testing, when this works for you i would recommend the following. we use a new constant and set this as an importing parameter for the _bind methods:
```abap
constants:
    begin of cs_compress_mode,
          full type string value `FULL`,                     "the way you need it for chart.js
          full_w_booleans type string value `FULL_W_BOOLEANS`,   "default value
          non type string value `NONE`,                    "old way in case the others are not working
     end of cs_compress_mode.
```

Do you think this will work for you?

**Comment by choper725** [comment]
seems good idea,

please check demo 153, i think there is an issue with the binds and compress

**Comment by oblomov-dev** [comment]
153 looks correct to me. The new compress logic is used which sends values typed with boolean to the frontend in any case.

specifically abap_bool = 'X' (abap_true) means true at the frontend and everything else becomes false, means '-' is false here at the frontend.

Normally I would not use abap_bool with values except abap_true or abap_false or why are you doing this?

**Comment by oblomov-dev** [comment]
abap2UI5 updated now with https://github.com/abap2UI5/abap2UI5/pull/799
<img width="453" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/31d28226-afcc-479c-8fcd-a0f2e64c57c3">

**Comment by choper725** [comment]
looking good,

native in class /ui2cl_/json, in case compress in activd:

when sending abap_false it not creating the structure,
but when sending ‘-‘ it create the struc with false as a value.
you overcome this in the framework checking the types explicitly.
but knowing that ‘-‘ creates a false value for a key in json with compress can solve the checking problem

**Comment by oblomov-dev** [comment]
(1) yes '-' becomes 'false', its done here:
https://github.com/abap2UI5/abap2UI5/blob/70da7816d89cd0e0e55b5a823a1f29954e73e502/src/00/z2ui5_cl_util_func.clas.abap#L302

(2) yes it is the default behaviour of /ui2/cl_json, when it is abap_false and the rest of the structure is also initial it gets not created and then it also does not matter if which comress mode you choose.

**Comment by choper725** [comment]
ui2/cl_json ignores initial values in compress, hence when the type is abap_bool and the value sent is ‘-‘ then its mapped to false.
 thats why in demo 153 i used ‘-‘ to show that the value is created in the json.

and when its set to abap_false it doesnt (what you changed in the demo)

**Comment by oblomov-dev** [comment]
ah ok i think i got your point now, instead of using abap_false we can use '-' or something else except 'X' to make /ui2/json do what we need. mhh yes thats right!

but this is still a bug to me of the /ui2/cl_json class and i am not sure if its a good idea to make it work with a trick. additionally i do not see a way how to map abap_false to '-'. For example when someone binds a table having a column with abap_bool, abap2UI5 throws it directly into the /ui2/cl_json class, adding here an extra loop for boolean checks would cost a lot of extr runtime and seems not a got idea to me... 

but still wondering, mhh maybe we will find a better way to solve this compression problem.

**Comment by choper725** [comment]
how do abap2ui5 handle abap_false binding? it doesnt check the types and values if each field??
